### PR TITLE
Fix: eask options should not be passed to buttercup

### PR DESCRIPTION
**Pull request by joshbax189**
E.g. before
```shell
> eask test buttercup --no-color
Package-file seems to be missing `buttercup.el'
  - Skipping buttercup (20240904.2311)... already installed ✗
Opening directory: No such file or directory, /home/naver/git/eask-cli/test/commands/test/buttercup/--eask--no-color
```

Fixed by setting `command-line-args-left` to the result of `eask-args` before calling `buttercup-run-discover`.

Another weird bug I noticed was that directories that are not children of the current directory are treated like empty directories.
Buttercup always fails, reporting 'No suites defined', even if there are test suites there. This can be kind of confusing, so I added an error for if the user tries to do this using `../`.
E.g. 
```shell
> eask test buttercup ../something
Buttercup cannot run in parent directories
```
However, this is also a problem when using an absolute directory that is not a child too
```shell
> pwd
/path/to/something/foo # something is the parent of the current dir
> eask test buttercup /path/to/something
No suites defined
```
You get this output even if there are buttercup tests in `/path/to/something`

If you want, I can test absolute paths too (i.e. check that every argument is on the load path/is reachable from the current directory), but I thought it might be a bit obscure? What do you think, is it worth checking?

### CODE REVIEW

**Comment by jcs090218** [comment]
> Fixed by setting command-line-args-left to the result of eask-args before calling buttercup-run-discover.

👍 

> Another weird bug I noticed was that directories that are not children of the current directory are treated like empty directories.
Buttercup always fails, reporting 'No suites defined', even if there are test suites there. This can be kind of confusing, so I added an error for if the user tries to do this using ../.

You are right. It's weird that `../` doesn't work. 🤔 Although this is confusing, I think it should be resolved from the upstream rather than by Eask.

> If you want, I can test absolute paths too (i.e. check that every argument is on the load path/is reachable from the current directory), but I thought it might be a bit obscure? What do you think, is it worth checking?

I don't think it's needed since those bugs are probably from buttercup itself and not from Eask. 

For example, I have been testing [Elsa](https://github.com/emacs-elsa/Elsa) in the past, but eventually, I had to get rid of it (see https://github.com/emacs-eask/cli/blob/master/test/commands/local/run.sh#L103) due to its instability. 🤔

**Comment by jcs090218** [comment]
> So keep or remove the existing warning? Maybe keeping it would prevent github issues from nosy people like me ;)

I prefer to remove it since making some noise can cause more people's attention. 🤔 But I guess reporting an error has the same effect. 

Let’s keep it and add a comment linking to this PR, so I can easily find and remember the reason behind this code. 😉

**Comment by joshbax189** [comment]
Done! Turns out it was pretty easy to check for both types of paths anyway. Also changed the warning message to include the specific path, just in case multiple paths were given.
```shell
> ~/git/eask-cli/bin/eask test buttercup ../ert
Buttercup cannot run in parent directory: ../ert
```

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Thank you! Merged! :D

**Pull request merged**
