### PR TITLE
feat(cask): Add option to convert Cask to Eask

### PR DESCRIPTION
**Pull request by jcs090218**
For #141. Add the options,

```
$ eask init --from cask [files..]
```

Another feature, the help instruction now look like this:

```
''                                                           ''

    Make sure you have a valid Cask-file in your directory

    Or specify Cask-file explicitly, like:

      $ eask init --from=cask /path/to/Cask

''                                                           ''
```

Expect for improvements.

### CODE REVIEW

**Comment by jcs090218** [comment]
Do you have Eask file in the directory? It will skip if there is already one presented. ;)

**Comment by Fuco1** [comment]
No Eask file.  I'm trying it in https://github.com/Fuco1/sphinx-mode repo now.

**Comment by jcs090218** [comment]
It works on my side. 🤔 

```
Running Eask in the development environment
Press Ctrl+C to cancel.

Executing script inside Emacs...

  Checking Emacs version 29.0.60... done!
  Checking system windows-nt... done!

Converting file `Cask` to `Eask`... done

(Total of 1 Cask-file converted)
```

The logic is here,

https://github.com/emacs-eask/cli/blob/52bd410e20a981b9065bb82211856b18e784c6c0/lisp/init/cask.el#L27-L38

It only checks for `(file-exists-p ...)` and `(string-prefix-p "Cask" ...)`.

**Comment by Fuco1** [comment]
Doesn't work for me not even on the master.  I'll try to debug it from source.

**Pull request merged**
